/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as DesktopPetRouteImport } from './routes/desktop-pet'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppSplatRouteImport } from './routes/_app/$'
import { Route as AppAllProjectsRouteImport } from './routes/_app/all-projects'
import { Route as AppAutomationsRouteImport } from './routes/_app/automations'
import { Route as AppBoardRouteImport } from './routes/_app/board'
import { Route as AppCommunityRouteImport } from './routes/_app/community'
import { Route as AppDraftsRouteImport } from './routes/_app/drafts'
import { Route as AppIntegrationsRouteImport } from './routes/_app/integrations'
import { Route as AppLibraryRouteImport } from './routes/_app/library'
import { Route as AppMembersRouteImport } from './routes/_app/members'
import { Route as AppOnboardingRouteImport } from './routes/_app/onboarding'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppTasksRouteImport } from './routes/_app/tasks'
import { Route as AppWorkspaceSettingsRouteImport } from './routes/_app/workspace-settings'
import { Route as AppBrandsIndexRouteImport } from './routes/_app/brands.index'
import { Route as AppBrandsBrandIdRouteImport } from './routes/_app/brands.$brandId'
import { Route as AppCollabDemoIndexRouteImport } from './routes/_app/collab-demo.index'
import { Route as AppCollabDemoProjectIdRouteImport } from './routes/_app/collab-demo.$projectId'
import { Route as AppDesignSystemsIndexRouteImport } from './routes/_app/design-systems.index'
import { Route as AppDesignSystemsDesignSystemIdRouteImport } from './routes/_app/design-systems.$designSystemId'
import { Route as AppDesignSystemsCreateRouteImport } from './routes/_app/design-systems.create'
import { Route as AppMarketplaceIndexRouteImport } from './routes/_app/marketplace.index'
import { Route as AppMarketplacePluginIdRouteImport } from './routes/_app/marketplace.$pluginId'
import { Route as AppPluginsIndexRouteImport } from './routes/_app/plugins.index'
import { Route as AppPluginsPluginIdRouteImport } from './routes/_app/plugins.$pluginId'
import { Route as AppProjectsIndexRouteImport } from './routes/_app/projects.index'
import { Route as AppProjectsProjectIdRouteImport } from './routes/_app/projects.$projectId'
import { Route as AppProjectsProjectIdConversationsConversationIdRouteImport } from './routes/_app/projects.$projectId.conversations.$conversationId'
import { Route as AppProjectsProjectIdFilesSplatRouteImport } from './routes/_app/projects.$projectId.files.$'
import { Route as AppProjectsProjectIdConversationsConversationIdFilesSplatRouteImport } from './routes/_app/projects.$projectId.conversations.$conversationId.files.$'

const AppRoute = AppRouteImport.update({
            id: '/_app',getParentRoute: () => rootRouteImport
          }as any)
const DesktopPetRoute = DesktopPetRouteImport.update({
            id: '/desktop-pet',path: '/desktop-pet',getParentRoute: () => rootRouteImport
          }as any)
const AppIndexRoute = AppIndexRouteImport.update({
            id: '/',path: '/',getParentRoute: () => AppRoute
          }as any)
const AppSplatRoute = AppSplatRouteImport.update({
            id: '/$',path: '/$',getParentRoute: () => AppRoute
          }as any)
const AppAllProjectsRoute = AppAllProjectsRouteImport.update({
            id: '/all-projects',path: '/all-projects',getParentRoute: () => AppRoute
          }as any)
const AppAutomationsRoute = AppAutomationsRouteImport.update({
            id: '/automations',path: '/automations',getParentRoute: () => AppRoute
          }as any)
const AppBoardRoute = AppBoardRouteImport.update({
            id: '/board',path: '/board',getParentRoute: () => AppRoute
          }as any)
const AppCommunityRoute = AppCommunityRouteImport.update({
            id: '/community',path: '/community',getParentRoute: () => AppRoute
          }as any)
const AppDraftsRoute = AppDraftsRouteImport.update({
            id: '/drafts',path: '/drafts',getParentRoute: () => AppRoute
          }as any)
const AppIntegrationsRoute = AppIntegrationsRouteImport.update({
            id: '/integrations',path: '/integrations',getParentRoute: () => AppRoute
          }as any)
const AppLibraryRoute = AppLibraryRouteImport.update({
            id: '/library',path: '/library',getParentRoute: () => AppRoute
          }as any)
const AppMembersRoute = AppMembersRouteImport.update({
            id: '/members',path: '/members',getParentRoute: () => AppRoute
          }as any)
const AppOnboardingRoute = AppOnboardingRouteImport.update({
            id: '/onboarding',path: '/onboarding',getParentRoute: () => AppRoute
          }as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
            id: '/settings',path: '/settings',getParentRoute: () => AppRoute
          }as any)
const AppTasksRoute = AppTasksRouteImport.update({
            id: '/tasks',path: '/tasks',getParentRoute: () => AppRoute
          }as any)
const AppWorkspaceSettingsRoute = AppWorkspaceSettingsRouteImport.update({
            id: '/workspace-settings',path: '/workspace-settings',getParentRoute: () => AppRoute
          }as any)
const AppBrandsIndexRoute = AppBrandsIndexRouteImport.update({
            id: '/brands/',path: '/brands/',getParentRoute: () => AppRoute
          }as any)
const AppBrandsBrandIdRoute = AppBrandsBrandIdRouteImport.update({
            id: '/brands/$brandId',path: '/brands/$brandId',getParentRoute: () => AppRoute
          }as any)
const AppCollabDemoIndexRoute = AppCollabDemoIndexRouteImport.update({
            id: '/collab-demo/',path: '/collab-demo/',getParentRoute: () => AppRoute
          }as any)
const AppCollabDemoProjectIdRoute = AppCollabDemoProjectIdRouteImport.update({
            id: '/collab-demo/$projectId',path: '/collab-demo/$projectId',getParentRoute: () => AppRoute
          }as any)
const AppDesignSystemsIndexRoute = AppDesignSystemsIndexRouteImport.update({
            id: '/design-systems/',path: '/design-systems/',getParentRoute: () => AppRoute
          }as any)
const AppDesignSystemsDesignSystemIdRoute = AppDesignSystemsDesignSystemIdRouteImport.update({
            id: '/design-systems/$designSystemId',path: '/design-systems/$designSystemId',getParentRoute: () => AppRoute
          }as any)
const AppDesignSystemsCreateRoute = AppDesignSystemsCreateRouteImport.update({
            id: '/design-systems/create',path: '/design-systems/create',getParentRoute: () => AppRoute
          }as any)
const AppMarketplaceIndexRoute = AppMarketplaceIndexRouteImport.update({
            id: '/marketplace/',path: '/marketplace/',getParentRoute: () => AppRoute
          }as any)
const AppMarketplacePluginIdRoute = AppMarketplacePluginIdRouteImport.update({
            id: '/marketplace/$pluginId',path: '/marketplace/$pluginId',getParentRoute: () => AppRoute
          }as any)
const AppPluginsIndexRoute = AppPluginsIndexRouteImport.update({
            id: '/plugins/',path: '/plugins/',getParentRoute: () => AppRoute
          }as any)
const AppPluginsPluginIdRoute = AppPluginsPluginIdRouteImport.update({
            id: '/plugins/$pluginId',path: '/plugins/$pluginId',getParentRoute: () => AppRoute
          }as any)
const AppProjectsIndexRoute = AppProjectsIndexRouteImport.update({
            id: '/projects/',path: '/projects/',getParentRoute: () => AppRoute
          }as any)
const AppProjectsProjectIdRoute = AppProjectsProjectIdRouteImport.update({
            id: '/projects/$projectId',path: '/projects/$projectId',getParentRoute: () => AppRoute
          }as any)
const AppProjectsProjectIdConversationsConversationIdRoute = AppProjectsProjectIdConversationsConversationIdRouteImport.update({
            id: '/conversations/$conversationId',path: '/conversations/$conversationId',getParentRoute: () => AppProjectsProjectIdRoute
          }as any)
const AppProjectsProjectIdFilesSplatRoute = AppProjectsProjectIdFilesSplatRouteImport.update({
            id: '/files/$',path: '/files/$',getParentRoute: () => AppProjectsProjectIdRoute
          }as any)
const AppProjectsProjectIdConversationsConversationIdFilesSplatRoute = AppProjectsProjectIdConversationsConversationIdFilesSplatRouteImport.update({
            id: '/files/$',path: '/files/$',getParentRoute: () => AppProjectsProjectIdConversationsConversationIdRoute
          }as any)

export interface FileRoutesByFullPath {
'/': typeof AppIndexRoute,'/desktop-pet': typeof DesktopPetRoute,'/$': typeof AppSplatRoute,'/all-projects': typeof AppAllProjectsRoute,'/automations': typeof AppAutomationsRoute,'/board': typeof AppBoardRoute,'/community': typeof AppCommunityRoute,'/drafts': typeof AppDraftsRoute,'/integrations': typeof AppIntegrationsRoute,'/library': typeof AppLibraryRoute,'/members': typeof AppMembersRoute,'/onboarding': typeof AppOnboardingRoute,'/settings': typeof AppSettingsRoute,'/tasks': typeof AppTasksRoute,'/workspace-settings': typeof AppWorkspaceSettingsRoute,'/brands/$brandId': typeof AppBrandsBrandIdRoute,'/collab-demo/$projectId': typeof AppCollabDemoProjectIdRoute,'/design-systems/$designSystemId': typeof AppDesignSystemsDesignSystemIdRoute,'/design-systems/create': typeof AppDesignSystemsCreateRoute,'/marketplace/$pluginId': typeof AppMarketplacePluginIdRoute,'/plugins/$pluginId': typeof AppPluginsPluginIdRoute,'/projects/$projectId': typeof AppProjectsProjectIdRouteWithChildren,'/brands/': typeof AppBrandsIndexRoute,'/collab-demo/': typeof AppCollabDemoIndexRoute,'/design-systems/': typeof AppDesignSystemsIndexRoute,'/marketplace/': typeof AppMarketplaceIndexRoute,'/plugins/': typeof AppPluginsIndexRoute,'/projects/': typeof AppProjectsIndexRoute,'/projects/$projectId/conversations/$conversationId': typeof AppProjectsProjectIdConversationsConversationIdRouteWithChildren,'/projects/$projectId/files/$': typeof AppProjectsProjectIdFilesSplatRoute,'/projects/$projectId/conversations/$conversationId/files/$': typeof AppProjectsProjectIdConversationsConversationIdFilesSplatRoute
}
export interface FileRoutesByTo {
'/desktop-pet': typeof DesktopPetRoute,'/$': typeof AppSplatRoute,'/all-projects': typeof AppAllProjectsRoute,'/automations': typeof AppAutomationsRoute,'/board': typeof AppBoardRoute,'/community': typeof AppCommunityRoute,'/drafts': typeof AppDraftsRoute,'/integrations': typeof AppIntegrationsRoute,'/library': typeof AppLibraryRoute,'/members': typeof AppMembersRoute,'/onboarding': typeof AppOnboardingRoute,'/settings': typeof AppSettingsRoute,'/tasks': typeof AppTasksRoute,'/workspace-settings': typeof AppWorkspaceSettingsRoute,'/': typeof AppIndexRoute,'/brands/$brandId': typeof AppBrandsBrandIdRoute,'/collab-demo/$projectId': typeof AppCollabDemoProjectIdRoute,'/design-systems/$designSystemId': typeof AppDesignSystemsDesignSystemIdRoute,'/design-systems/create': typeof AppDesignSystemsCreateRoute,'/marketplace/$pluginId': typeof AppMarketplacePluginIdRoute,'/plugins/$pluginId': typeof AppPluginsPluginIdRoute,'/projects/$projectId': typeof AppProjectsProjectIdRouteWithChildren,'/brands': typeof AppBrandsIndexRoute,'/collab-demo': typeof AppCollabDemoIndexRoute,'/design-systems': typeof AppDesignSystemsIndexRoute,'/marketplace': typeof AppMarketplaceIndexRoute,'/plugins': typeof AppPluginsIndexRoute,'/projects': typeof AppProjectsIndexRoute,'/projects/$projectId/conversations/$conversationId': typeof AppProjectsProjectIdConversationsConversationIdRouteWithChildren,'/projects/$projectId/files/$': typeof AppProjectsProjectIdFilesSplatRoute,'/projects/$projectId/conversations/$conversationId/files/$': typeof AppProjectsProjectIdConversationsConversationIdFilesSplatRoute
}
export interface FileRoutesById {
'__root__': typeof rootRouteImport,
'/_app': typeof AppRouteWithChildren,'/desktop-pet': typeof DesktopPetRoute,'/_app/$': typeof AppSplatRoute,'/_app/all-projects': typeof AppAllProjectsRoute,'/_app/automations': typeof AppAutomationsRoute,'/_app/board': typeof AppBoardRoute,'/_app/community': typeof AppCommunityRoute,'/_app/drafts': typeof AppDraftsRoute,'/_app/integrations': typeof AppIntegrationsRoute,'/_app/library': typeof AppLibraryRoute,'/_app/members': typeof AppMembersRoute,'/_app/onboarding': typeof AppOnboardingRoute,'/_app/settings': typeof AppSettingsRoute,'/_app/tasks': typeof AppTasksRoute,'/_app/workspace-settings': typeof AppWorkspaceSettingsRoute,'/_app/': typeof AppIndexRoute,'/_app/brands/$brandId': typeof AppBrandsBrandIdRoute,'/_app/collab-demo/$projectId': typeof AppCollabDemoProjectIdRoute,'/_app/design-systems/$designSystemId': typeof AppDesignSystemsDesignSystemIdRoute,'/_app/design-systems/create': typeof AppDesignSystemsCreateRoute,'/_app/marketplace/$pluginId': typeof AppMarketplacePluginIdRoute,'/_app/plugins/$pluginId': typeof AppPluginsPluginIdRoute,'/_app/projects/$projectId': typeof AppProjectsProjectIdRouteWithChildren,'/_app/brands/': typeof AppBrandsIndexRoute,'/_app/collab-demo/': typeof AppCollabDemoIndexRoute,'/_app/design-systems/': typeof AppDesignSystemsIndexRoute,'/_app/marketplace/': typeof AppMarketplaceIndexRoute,'/_app/plugins/': typeof AppPluginsIndexRoute,'/_app/projects/': typeof AppProjectsIndexRoute,'/_app/projects/$projectId/conversations/$conversationId': typeof AppProjectsProjectIdConversationsConversationIdRouteWithChildren,'/_app/projects/$projectId/files/$': typeof AppProjectsProjectIdFilesSplatRoute,'/_app/projects/$projectId/conversations/$conversationId/files/$': typeof AppProjectsProjectIdConversationsConversationIdFilesSplatRoute
}
export interface FileRouteTypes {
fileRoutesByFullPath: FileRoutesByFullPath
fullPaths: '/'|'/desktop-pet'|'/$'|'/all-projects'|'/automations'|'/board'|'/community'|'/drafts'|'/integrations'|'/library'|'/members'|'/onboarding'|'/settings'|'/tasks'|'/workspace-settings'|'/brands/$brandId'|'/collab-demo/$projectId'|'/design-systems/$designSystemId'|'/design-systems/create'|'/marketplace/$pluginId'|'/plugins/$pluginId'|'/projects/$projectId'|'/brands/'|'/collab-demo/'|'/design-systems/'|'/marketplace/'|'/plugins/'|'/projects/'|'/projects/$projectId/conversations/$conversationId'|'/projects/$projectId/files/$'|'/projects/$projectId/conversations/$conversationId/files/$'
fileRoutesByTo: FileRoutesByTo
to: '/desktop-pet'|'/$'|'/all-projects'|'/automations'|'/board'|'/community'|'/drafts'|'/integrations'|'/library'|'/members'|'/onboarding'|'/settings'|'/tasks'|'/workspace-settings'|'/'|'/brands/$brandId'|'/collab-demo/$projectId'|'/design-systems/$designSystemId'|'/design-systems/create'|'/marketplace/$pluginId'|'/plugins/$pluginId'|'/projects/$projectId'|'/brands'|'/collab-demo'|'/design-systems'|'/marketplace'|'/plugins'|'/projects'|'/projects/$projectId/conversations/$conversationId'|'/projects/$projectId/files/$'|'/projects/$projectId/conversations/$conversationId/files/$'
id: '__root__'|'/_app'|'/desktop-pet'|'/_app/$'|'/_app/all-projects'|'/_app/automations'|'/_app/board'|'/_app/community'|'/_app/drafts'|'/_app/integrations'|'/_app/library'|'/_app/members'|'/_app/onboarding'|'/_app/settings'|'/_app/tasks'|'/_app/workspace-settings'|'/_app/'|'/_app/brands/$brandId'|'/_app/collab-demo/$projectId'|'/_app/design-systems/$designSystemId'|'/_app/design-systems/create'|'/_app/marketplace/$pluginId'|'/_app/plugins/$pluginId'|'/_app/projects/$projectId'|'/_app/brands/'|'/_app/collab-demo/'|'/_app/design-systems/'|'/_app/marketplace/'|'/_app/plugins/'|'/_app/projects/'|'/_app/projects/$projectId/conversations/$conversationId'|'/_app/projects/$projectId/files/$'|'/_app/projects/$projectId/conversations/$conversationId/files/$'
fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
AppRoute: typeof AppRouteWithChildren,DesktopPetRoute: typeof DesktopPetRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
          id: '/_app'
          path: ''
          fullPath: '/'
          preLoaderRoute: typeof AppRouteImport
          parentRoute: typeof rootRouteImport
        }
'/desktop-pet': {
          id: '/desktop-pet'
          path: '/desktop-pet'
          fullPath: '/desktop-pet'
          preLoaderRoute: typeof DesktopPetRouteImport
          parentRoute: typeof rootRouteImport
        }
'/_app/': {
          id: '/_app/'
          path: '/'
          fullPath: '/'
          preLoaderRoute: typeof AppIndexRouteImport
          parentRoute: typeof AppRoute
        }
'/_app/$': {
          id: '/_app/$'
          path: '/$'
          fullPath: '/$'
          preLoaderRoute: typeof AppSplatRouteImport
          parentRoute: typeof AppRoute
        }
'/_app/all-projects': {
          id: '/_app/all-projects'
          path: '/all-projects'
          fullPath: '/all-projects'
          preLoaderRoute: typeof AppAllProjectsRouteImport
          parentRoute: typeof AppRoute
        }
'/_app/automations': {
          id: '/_app/automations'
          path: '/automations'
          fullPath: '/automations'
          preLoaderRoute: typeof AppAutomationsRouteImport
          parentRoute: typeof AppRoute
        }
'/_app/board': {
          id: '/_app/board'
          path: '/board'
          fullPath: '/board'
          preLoaderRoute: typeof AppBoardRouteImport
          parentRoute: typeof AppRoute
        }
'/_app/community': {
          id: '/_app/community'
          path: '/community'
          fullPath: '/community'
          preLoaderRoute: typeof AppCommunityRouteImport
          parentRoute: typeof AppRoute
        }
'/_app/drafts': {
          id: '/_app/drafts'
          path: '/drafts'
          fullPath: '/drafts'
          preLoaderRoute: typeof AppDraftsRouteImport
          parentRoute: typeof AppRoute
        }
'/_app/integrations': {
          id: '/_app/integrations'
          path: '/integrations'
          fullPath: '/integrations'
          preLoaderRoute: typeof AppIntegrationsRouteImport
          parentRoute: typeof AppRoute
        }
'/_app/library': {
          id: '/_app/library'
          path: '/library'
          fullPath: '/library'
          preLoaderRoute: typeof AppLibraryRouteImport
          parentRoute: typeof AppRoute
        }
'/_app/members': {
          id: '/_app/members'
          path: '/members'
          fullPath: '/members'
          preLoaderRoute: typeof AppMembersRouteImport
          parentRoute: typeof AppRoute
        }
'/_app/onboarding': {
          id: '/_app/onboarding'
          path: '/onboarding'
          fullPath: '/onboarding'
          preLoaderRoute: typeof AppOnboardingRouteImport
          parentRoute: typeof AppRoute
        }
'/_app/settings': {
          id: '/_app/settings'
          path: '/settings'
          fullPath: '/settings'
          preLoaderRoute: typeof AppSettingsRouteImport
          parentRoute: typeof AppRoute
        }
'/_app/tasks': {
          id: '/_app/tasks'
          path: '/tasks'
          fullPath: '/tasks'
          preLoaderRoute: typeof AppTasksRouteImport
          parentRoute: typeof AppRoute
        }
'/_app/workspace-settings': {
          id: '/_app/workspace-settings'
          path: '/workspace-settings'
          fullPath: '/workspace-settings'
          preLoaderRoute: typeof AppWorkspaceSettingsRouteImport
          parentRoute: typeof AppRoute
        }
'/_app/brands/': {
          id: '/_app/brands/'
          path: '/brands'
          fullPath: '/brands/'
          preLoaderRoute: typeof AppBrandsIndexRouteImport
          parentRoute: typeof AppRoute
        }
'/_app/brands/$brandId': {
          id: '/_app/brands/$brandId'
          path: '/brands/$brandId'
          fullPath: '/brands/$brandId'
          preLoaderRoute: typeof AppBrandsBrandIdRouteImport
          parentRoute: typeof AppRoute
        }
'/_app/collab-demo/': {
          id: '/_app/collab-demo/'
          path: '/collab-demo'
          fullPath: '/collab-demo/'
          preLoaderRoute: typeof AppCollabDemoIndexRouteImport
          parentRoute: typeof AppRoute
        }
'/_app/collab-demo/$projectId': {
          id: '/_app/collab-demo/$projectId'
          path: '/collab-demo/$projectId'
          fullPath: '/collab-demo/$projectId'
          preLoaderRoute: typeof AppCollabDemoProjectIdRouteImport
          parentRoute: typeof AppRoute
        }
'/_app/design-systems/': {
          id: '/_app/design-systems/'
          path: '/design-systems'
          fullPath: '/design-systems/'
          preLoaderRoute: typeof AppDesignSystemsIndexRouteImport
          parentRoute: typeof AppRoute
        }
'/_app/design-systems/$designSystemId': {
          id: '/_app/design-systems/$designSystemId'
          path: '/design-systems/$designSystemId'
          fullPath: '/design-systems/$designSystemId'
          preLoaderRoute: typeof AppDesignSystemsDesignSystemIdRouteImport
          parentRoute: typeof AppRoute
        }
'/_app/design-systems/create': {
          id: '/_app/design-systems/create'
          path: '/design-systems/create'
          fullPath: '/design-systems/create'
          preLoaderRoute: typeof AppDesignSystemsCreateRouteImport
          parentRoute: typeof AppRoute
        }
'/_app/marketplace/': {
          id: '/_app/marketplace/'
          path: '/marketplace'
          fullPath: '/marketplace/'
          preLoaderRoute: typeof AppMarketplaceIndexRouteImport
          parentRoute: typeof AppRoute
        }
'/_app/marketplace/$pluginId': {
          id: '/_app/marketplace/$pluginId'
          path: '/marketplace/$pluginId'
          fullPath: '/marketplace/$pluginId'
          preLoaderRoute: typeof AppMarketplacePluginIdRouteImport
          parentRoute: typeof AppRoute
        }
'/_app/plugins/': {
          id: '/_app/plugins/'
          path: '/plugins'
          fullPath: '/plugins/'
          preLoaderRoute: typeof AppPluginsIndexRouteImport
          parentRoute: typeof AppRoute
        }
'/_app/plugins/$pluginId': {
          id: '/_app/plugins/$pluginId'
          path: '/plugins/$pluginId'
          fullPath: '/plugins/$pluginId'
          preLoaderRoute: typeof AppPluginsPluginIdRouteImport
          parentRoute: typeof AppRoute
        }
'/_app/projects/': {
          id: '/_app/projects/'
          path: '/projects'
          fullPath: '/projects/'
          preLoaderRoute: typeof AppProjectsIndexRouteImport
          parentRoute: typeof AppRoute
        }
'/_app/projects/$projectId': {
          id: '/_app/projects/$projectId'
          path: '/projects/$projectId'
          fullPath: '/projects/$projectId'
          preLoaderRoute: typeof AppProjectsProjectIdRouteImport
          parentRoute: typeof AppRoute
        }
'/_app/projects/$projectId/conversations/$conversationId': {
          id: '/_app/projects/$projectId/conversations/$conversationId'
          path: '/conversations/$conversationId'
          fullPath: '/projects/$projectId/conversations/$conversationId'
          preLoaderRoute: typeof AppProjectsProjectIdConversationsConversationIdRouteImport
          parentRoute: typeof AppProjectsProjectIdRoute
        }
'/_app/projects/$projectId/files/$': {
          id: '/_app/projects/$projectId/files/$'
          path: '/files/$'
          fullPath: '/projects/$projectId/files/$'
          preLoaderRoute: typeof AppProjectsProjectIdFilesSplatRouteImport
          parentRoute: typeof AppProjectsProjectIdRoute
        }
'/_app/projects/$projectId/conversations/$conversationId/files/$': {
          id: '/_app/projects/$projectId/conversations/$conversationId/files/$'
          path: '/files/$'
          fullPath: '/projects/$projectId/conversations/$conversationId/files/$'
          preLoaderRoute: typeof AppProjectsProjectIdConversationsConversationIdFilesSplatRouteImport
          parentRoute: typeof AppProjectsProjectIdConversationsConversationIdRoute
        }
  }
}



interface AppProjectsProjectIdConversationsConversationIdRouteChildren {
  AppProjectsProjectIdConversationsConversationIdFilesSplatRoute: typeof AppProjectsProjectIdConversationsConversationIdFilesSplatRoute
}

const AppProjectsProjectIdConversationsConversationIdRouteChildren: AppProjectsProjectIdConversationsConversationIdRouteChildren = {
  AppProjectsProjectIdConversationsConversationIdFilesSplatRoute: AppProjectsProjectIdConversationsConversationIdFilesSplatRoute
}

const AppProjectsProjectIdConversationsConversationIdRouteWithChildren = AppProjectsProjectIdConversationsConversationIdRoute._addFileChildren(AppProjectsProjectIdConversationsConversationIdRouteChildren)

interface AppProjectsProjectIdRouteChildren {
  AppProjectsProjectIdConversationsConversationIdRoute: typeof AppProjectsProjectIdConversationsConversationIdRouteWithChildren,AppProjectsProjectIdFilesSplatRoute: typeof AppProjectsProjectIdFilesSplatRoute
}

const AppProjectsProjectIdRouteChildren: AppProjectsProjectIdRouteChildren = {
  AppProjectsProjectIdConversationsConversationIdRoute: AppProjectsProjectIdConversationsConversationIdRouteWithChildren,AppProjectsProjectIdFilesSplatRoute: AppProjectsProjectIdFilesSplatRoute
}

const AppProjectsProjectIdRouteWithChildren = AppProjectsProjectIdRoute._addFileChildren(AppProjectsProjectIdRouteChildren)

interface AppRouteChildren {
  AppSplatRoute: typeof AppSplatRoute,AppAllProjectsRoute: typeof AppAllProjectsRoute,AppAutomationsRoute: typeof AppAutomationsRoute,AppBoardRoute: typeof AppBoardRoute,AppCommunityRoute: typeof AppCommunityRoute,AppDraftsRoute: typeof AppDraftsRoute,AppIntegrationsRoute: typeof AppIntegrationsRoute,AppLibraryRoute: typeof AppLibraryRoute,AppMembersRoute: typeof AppMembersRoute,AppOnboardingRoute: typeof AppOnboardingRoute,AppSettingsRoute: typeof AppSettingsRoute,AppTasksRoute: typeof AppTasksRoute,AppWorkspaceSettingsRoute: typeof AppWorkspaceSettingsRoute,AppIndexRoute: typeof AppIndexRoute,AppBrandsBrandIdRoute: typeof AppBrandsBrandIdRoute,AppCollabDemoProjectIdRoute: typeof AppCollabDemoProjectIdRoute,AppDesignSystemsDesignSystemIdRoute: typeof AppDesignSystemsDesignSystemIdRoute,AppDesignSystemsCreateRoute: typeof AppDesignSystemsCreateRoute,AppMarketplacePluginIdRoute: typeof AppMarketplacePluginIdRoute,AppPluginsPluginIdRoute: typeof AppPluginsPluginIdRoute,AppProjectsProjectIdRoute: typeof AppProjectsProjectIdRouteWithChildren,AppBrandsIndexRoute: typeof AppBrandsIndexRoute,AppCollabDemoIndexRoute: typeof AppCollabDemoIndexRoute,AppDesignSystemsIndexRoute: typeof AppDesignSystemsIndexRoute,AppMarketplaceIndexRoute: typeof AppMarketplaceIndexRoute,AppPluginsIndexRoute: typeof AppPluginsIndexRoute,AppProjectsIndexRoute: typeof AppProjectsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppSplatRoute: AppSplatRoute,AppAllProjectsRoute: AppAllProjectsRoute,AppAutomationsRoute: AppAutomationsRoute,AppBoardRoute: AppBoardRoute,AppCommunityRoute: AppCommunityRoute,AppDraftsRoute: AppDraftsRoute,AppIntegrationsRoute: AppIntegrationsRoute,AppLibraryRoute: AppLibraryRoute,AppMembersRoute: AppMembersRoute,AppOnboardingRoute: AppOnboardingRoute,AppSettingsRoute: AppSettingsRoute,AppTasksRoute: AppTasksRoute,AppWorkspaceSettingsRoute: AppWorkspaceSettingsRoute,AppIndexRoute: AppIndexRoute,AppBrandsBrandIdRoute: AppBrandsBrandIdRoute,AppCollabDemoProjectIdRoute: AppCollabDemoProjectIdRoute,AppDesignSystemsDesignSystemIdRoute: AppDesignSystemsDesignSystemIdRoute,AppDesignSystemsCreateRoute: AppDesignSystemsCreateRoute,AppMarketplacePluginIdRoute: AppMarketplacePluginIdRoute,AppPluginsPluginIdRoute: AppPluginsPluginIdRoute,AppProjectsProjectIdRoute: AppProjectsProjectIdRouteWithChildren,AppBrandsIndexRoute: AppBrandsIndexRoute,AppCollabDemoIndexRoute: AppCollabDemoIndexRoute,AppDesignSystemsIndexRoute: AppDesignSystemsIndexRoute,AppMarketplaceIndexRoute: AppMarketplaceIndexRoute,AppPluginsIndexRoute: AppPluginsIndexRoute,AppProjectsIndexRoute: AppProjectsIndexRoute
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,DesktopPetRoute: DesktopPetRoute
}
export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)._addFileTypes<FileRouteTypes>()